#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

define("PHP_DIR", __DIR__ . "/php-project-manage");

require PHP_DIR . '/vendor/autoload.php';
require PHP_DIR . '/vendor/yiisoft/yii2/Yii.php';

$config = require PHP_DIR . '/config/console.php';

$application = new \yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);